[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[build]
  command = "npm run build"  # Or the command you use to build your project
  publish = "build"          # Or the directory where the built files are located
